import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateMath,parseManualDice,newRound,recordSolution,scoreFor,evaluateForRound} from '../math.js';
import {findHint} from '../hints.js';
for(const [expression,expected] of [['3!-2',4],['2^-1',.5],['2+3*4',14],['(2+3)*4',20],['2^3^2',512],['-2^2',-4],['(-2)^2',4],['0!',1],['1!',1],['6/3*2',4],['(1/3)*3',1],['4^(1/2)',2],['2--3',5]])test(`Mathematics: ${expression}`,()=>assert.equal(calculateMath(expression),expected));
for(const expression of ['!3','2++3','2(3)','(2+3','2+3)','()','2/0','3**2','2.5','23','alert(1)','9!!!','(9^9)!','0^-1'])test(`Reject malformed or unsafe: ${expression}`,()=>assert.throws(()=>calculateMath(expression)));
test('Dice are a multiset, not a set',()=>{assert.equal(evaluateForRound('4/4',[4,4,1,2,3]),1);assert.throws(()=>evaluateForRound('4/4',[4,5,1,2,3]));});
test('Unicode mathematical operators work',()=>assert.equal(evaluateForRound('6 ÷ 3 − 1',[6,3,1,4,5]),1));
test('Fractional intermediate results are legal',()=>assert.equal(evaluateForRound('(1/3)*3',[1,3,3,4,5]),1));
test('Fractional, negative and zero final results are not solutions',()=>{for(const expr of ['1/3','1-3','3-3'])assert.throws(()=>evaluateForRound(expr,[1,3,3,4,5]));});
test('Manual dice are parsed strictly',()=>{assert.deepEqual(parseManualDice('0, 3, 4, 9, 5'),[0,3,4,9,5]);for(const input of ['1x,2,3,4,5','1.5,2,3,4,5','1,2,3,4,5,abc','11,2,3,4,5','1,2,3,4'])assert.throws(()=>parseManualDice(input));});
test('Success keeps the exact original cast and advances the target',()=>{const round=newRound([1,2,3,4,5]);round.tokens=[{value:'1',die:0}];const next=recordSolution(round,'1');assert.deepEqual(next.dice,round.dice);assert.equal(scoreFor(next.solutions),1);assert.deepEqual(next.tokens,[]);assert.deepEqual(round.solutions,{});});
test('New round clears all solutions and starts at 1, with exactly five dice',()=>{let round=recordSolution(newRound([1,2,3,4,5]),'1');round=recordSolution(round,'2');const reset=newRound([6,6,2,2,3],round.mode,round.level);assert.equal(scoreFor(reset.solutions)+1,1);assert.deepEqual(reset.solutions,{});assert.deepEqual(reset.tokens,[]);assert.equal(reset.dice.length,5);});
test('Sequential mode rejects an out of order result',()=>assert.throws(()=>recordSolution(newRound([1,2,3,4,5]),'3')));
test('Freestyle fills gaps; switching mode preserves the cast and shared progress',()=>{let round=newRound([1,2,3,4,5],'freestyle');round=recordSolution(round,'1');round=recordSolution(round,'3');assert.equal(scoreFor(round.solutions),1);round.mode='sequential';round=recordSolution(round,'2');assert.equal(scoreFor(round.solutions),3);assert.deepEqual(round.dice,[1,2,3,4,5]);});
test('Duplicates are rejected',()=>{let round=recordSolution(newRound([1,2,3,4,5],'freestyle'),'1');assert.throws(()=>recordSolution(round,'1'));});
test('Advanced operators obey selected level',()=>{assert.throws(()=>evaluateForRound('3!',[1,2,3,4,5],'basic'));assert.equal(evaluateForRound('3!',[1,2,3,4,5],'advanced'),6);});
for(const dice of [[1,2,3,4,5],[6,6,6,6,6],[0,0,1,1,2],[2,2,3,5,6]])test(`Hints use only available dice: ${dice}`,()=>{for(let n=1;n<=15;n++){const expr=findHint(dice,n,'basic');if(expr)assert.equal(evaluateForRound(expr,dice,'basic'),n);}});
test('Advanced hints are also validated',()=>{const dice=[3,3,3,3,3];const expr=findHint(dice,6,'advanced');assert.ok(expr);assert.equal(evaluateForRound(expr,dice,'advanced'),6);});
test('A tiny fraction is not rounded into a valid whole-number answer',()=>assert.throws(()=>evaluateForRound('1+2^(-9*6)',[1,2,9,6,4],'advanced')));
test('Exact rational cancellation remains valid',()=>assert.equal(evaluateForRound('(1/3+2/3)*3',[1,3,2,3,3],'advanced'),3));
